[package]
name = "floc"
authors = ["Romain Chardiny <romain.chardiny@gmail.com>"]
description = "Flo Compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo"] }
lazy_static = "1.4.0"
pest = "2.7.10"
pest_derive = "2.7.10"
tempfile = "3.10.1"
thiserror = "1.0.61"

[target.'cfg(not(windows))'.dependencies]
inkwell = { version = "0.4.0", features = ["llvm17-0-prefer-dynamic"] }

[target.'cfg(windows)'.dependencies]
inkwell = { version = "0.4.0", features = ["llvm17-0-force-static", "target-x86"], default-features = false }
